"""empty message

Revision ID: 33862f68a9f1
Revises: 2291f182e4f1
Create Date: 2023-04-13 14:45:27.370199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33862f68a9f1'
down_revision = '2291f182e4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_people', sa.Integer(), nullable=True),
    sa.Column('id_planets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_people'], ['people.id'], ),
    sa.ForeignKeyConstraint(['id_planets'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
