"""empty message

Revision ID: 4d5ad360c86b
Revises: 33862f68a9f1
Create Date: 2023-04-13 15:05:09.838048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5ad360c86b'
down_revision = '33862f68a9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('people_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_id_people_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_id_planets_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_id_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'])
        batch_op.drop_column('id_people')
        batch_op.drop_column('id_planets')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_planets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_people', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_id_user_fkey', 'user', ['id_user'], ['id'])
        batch_op.create_foreign_key('favorites_id_planets_fkey', 'planet', ['id_planets'], ['id'])
        batch_op.create_foreign_key('favorites_id_people_fkey', 'people', ['id_people'], ['id'])
        batch_op.drop_column('planet_id')
        batch_op.drop_column('people_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
